save_data = struct();
save_data.Model_Rs = Model_Rs;
save_data.FitModels = FitModels;
save_data.Param = Param;
% getmodelfiledir(filepath), ...
parsave(...
    Param.get_model_dir, ...
    sprintf('%s.mat', Param.get_save_file_name(filepath)), ...
    save_data ...
    );

fprintf(logfile, '\n\n\nCompleted!\n');
fclose(logfile);

updatacompletedata(filepath, Param);